### ISSUE TITLE
Crash "pointer being freed was not allocated" v2.6.0

### ISSUE THREAD

**Issue by KoxarasA** [akamai/mPulse-iOS#11]
When we use the mPulse 2.6.0 we get a crash very often with the following output:

OurApp(52271,0x70000cb11000) malloc: *** error for object 0x600001746c60: pointer being freed was not allocated
OurApp(52271,0x70000cb11000) malloc: *** set a breakpoint in malloc_error_break to debug

The issue occurs at start up, when we initialise Soasta, set the view group, start a timer and set 3-4 times a custom dimension. All these commands run on the main thread very quickly. It seems however that the loading of a config file causes this crash

More information (including output from a run with the address sanitizer on) can be seen at: https://gist.github.com/KoxarasA/867cf0c833f5eb64619011ea6d7161ca

The issue does not happen when we downgrade to 2.3.6

**Comment by nicjansma** [comment]
Hi @KoxarasA!

We've fixed this issue in mPulse iOS SDK `2.6.1`.  Can you verify if that release works?

**Comment by KoxarasA** [comment]
Hi @nicjansma 

The issue is resolved! Thank you!
